### ISSUE TITLE
CI script does not work with multiple .json files

### ISSUE THREAD

**Issue by alexandruast** [tharsis/testnets#2152]
When executing validate-gentxs.sh, the script expects a single json file:
```
GENTX_FILE=$(find $GENTXS_DIR -iname "*.json")
.
.
.
GENACC=$(cat $GENTX_FILE | sed -n 's|.*"delegator_address":"\([^"]*\)".*|\1|p')
```

After the team merged the first PR, the script no longer works.

**Comment by alexandruast** [comment]
This was the reason test.json was removed in the first place

**Comment by Darkstaff88** [comment]
yeah, waiting for fix

**Comment by justamomento** [comment]
Gaben fix Dota2 please!

**Comment by khoslaventures** [comment]
Thanks for bringing this up, we're gonna post a fix

**Comment by khoslaventures** [comment]
this has been fixed. #2468
