### ISSUE TITLE
evmos_9000-3 genesis validation

### ISSUE THREAD

**Issue by farmclubio** [tharsis/testnets#2847]
Unable to valid genesis json file with ```evmosd validate-genesis --trace```

- failed to unmarshal feemarket genesis state: unknown field "initial_base_fee" in types.Params
- failed to unmarshal feemarket genesis state: unknown field "base_fee" in types.GenesisState

And without this entries => error

EMVOS version : [v1.0.0-beta1](https://github.com/tharsis/evmos/releases/tag/v1.0.0-beta1)
Genesis used : #2845

**Comment by giansalex** [comment]
`unknown field`  it usually happens when you use the wrong binary, I was able to join the testnet-3

**Comment by farmclubio** [comment]
Witch version of binary you use ? v1.0.0-beta or release 0.4.2 ?

**Comment by tuvs85** [comment]
How did you fix this issue please?

**Comment by farmclubio** [comment]
Complete clean reinstall with the right bin version. With the genesis file in the repo

**Comment by leo-icp** [comment]
Very sorry, but I also encountered this problem, I tried it with 0.4.1 and 1.0.0, 1.1.0. . There is a connection field problem, can I ask you, how did you deploy it normally? What version of evmosd are you using?
