### ISSUE TITLE
ADD fible.json

### ISSUE THREAD

**Issue by Fible1** [tharsis/testnets#478]
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"fible1","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.100000000000000000","max_rate":"1.000000000000000000","max_change_rate":"0.100000000000000000"},"min_self_delegation":"1","delegator_address":"evmos1qta3gje4l3fmps3p2gz8gxa3kucg66nyqxmc4e","validator_address":"evmosvaloper1qta3gje4l3fmps3p2gz8gxa3kucg66nydg5g5y","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"RMuiSA9rT6NCIOgazVZo1TEg007GlSaMCRIHLPXltfg="},"value":{"denom":"aphoton","amount":"1000000000000"}}],"memo":"1e92f4ac535bc92fbd01327a7f286e6f4843d8a1@167.114.175.5:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/ethermint.crypto.v1.ethsecp256k1.PubKey","key":"A+BgHzodQM2g5SEzOHPDVuzmSLCOKOW5muEIZZI45fJ2"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":["jONdNNbjPXEPz5kjwxaty6/AYdsqfICqHLSi/HkkH3YKRpK/XWzroVUcSdNDLNb06sJO6MB3WDi34Emh/Dqy4AE="]}

**Comment by fedekunze** [comment]
please open a Pull Request

**Comment by Fible1** [comment]
Please see pull #1892. @fedekunze
